# GitHub Action for generating a contribution graph with a snake eating your contributions.
name: Generate Snake Animation

on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  
  # Allows manually running the job from the Actions tab
  workflow_dispatch:

  # Runs on every push to the main branch
  push:
    branches:
      - main
    
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Checkout the repository to access the files
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Generate the snake game as SVG and GIF for light and dark themes
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Luv2SeeYouCry
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake-dark.gif?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Push the generated SVG and GIF files to the output branch
      - name: Push generated snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Show the status of the build for debugging purposes
      - name: Show build status
        run: git status
